stages:
  - test

before_script:
  - docker info

test:
  stage: test
  script:
    - docker build -t pathgan-pytorch .
    - docker run pathgan-pytorch --gpus=all --rm python -m unittest discover tests
